title: Rise of the Robots
author: misandfo
description: > # this means to ignore newlines until "baseurl:"
  Lessons learnt and bots built in the #100DaysOfCode challenge
  
# social links
twitter_username: @msandfor
github_username:  @msandfor

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
